---
- name: Creating-EC2
  hosts: localhost
  connection: local
  tasks:
    - name: Start an instance with a public IP address
      amazon.aws.ec2_instance:
        name: "my-demo-ec2-instance"
        instance_type: t2.micro
        aws_access_key_id: '{{ ec2_access_key_id }}'
        aws_access_key: "{{ ec2_access_key }}"
        security_group: default
        network_interfaces:
          - assign_public_ip: true
        image_id: ami-0731becbf832f281e
        tags:
          Environment: Testing
