---
- name: Shutdown instance that belongs to ubuntu os
  hosts: all
  become: true
  tasks:
    - name: Debug ansible facts
      ansible.builtin.debug:
        var: ansible_facts
        # msg: "{{ ansible_facts | tojson }}"

    - name: Turning off running ubuntu/redhat os
      ansible.builtin.command: shutdown -h now
      changed_when: false
      when:
        - ansible_facts.os_family == 'Debian'
        # - ansible_facts.os_family == 'RedHat' # Tested with RedHat OS family as well
